eureka:
  instance:
    hostname: ${APP_NAME:spring.application.name}.herokuapp.com
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SVR_URL:https://admin:naming-server-eureka@naming-server-first.herokuapp.com}/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/uaa/user/current #http://localhost:8081/uaa/user/current
      token-info-uri: http://auth-service/uaa/oauth/check_token
