eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: https://naming-server-first.herokuapp.com/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/uaa/user/current #http://localhost:8081/uaa/user/current
      token-info-uri: http://auth-service/uaa/oauth/check_token
