server:
  port: 8082
  servlet:
    context-path: /uaa

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ftapp
    password: ftapp
    driver-class-name: oracle.jdbc.driver.OracleDriver
